### ISSUE TITLE
Update github controller

### ISSUE THREAD

**Issue by NealArw** [UffizziCloud/uffizzi_controller#32]
Update make file. Needs to transfer data from GitLab to GitHub. 
Repo on the GitHub have some difference between GitLab.
E.g. In the GitHub controller does not work command `make setup_gke_kube`

**Comment by moklidia** [comment]
@NealArw You should be able to build the toolbox and use the `make setup_gke_kube` command. The Kubernetes commands have been updated in OnePassword.

**Comment by NealArw** [comment]
**TESTED - OK**
