### ISSUE TITLE
Increase volume size from 1Gi to 5Gi

### ISSUE THREAD

**Issue by axisofentropy** [UffizziCloud/uffizzi_controller#41]
A customer has a 1.9GB database they'd like to import to a persistent volume. It looks like the GCE virtual disk volumes are only $0.04/month/GiB so we're going to increase from 1GiB to 5GiB.

Support thread (internal) https://uffizzi-internal.slack.com/archives/CN4255W79/p1665633562421119?thread_ts=1665501099.686279&cid=CN4255W79

**Comment by moklidia** [comment]
Merged and released
