### ISSUE TITLE
Add 404 when namespace not found

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi_controller#54]
When we find, update, delete namespace we sent error to sentry if namespace not found. For avoid this we should extract 404

E.g. [error](https://sentry.io/organizations/uffizzi-cloud/issues/2929879154/?project=1833351&query=is%3Aunresolved&referrer=issue-stream)

### HOW TO TEST: ###
1. Try to create deployment
Expected: all should be good

2. Try to update deployment
Expected: all should be good

3. Try to delete deployment
Expected: all should be good

**Comment by fedorov-dualboot** [comment]
tested. **OK**

- create deployment

Actual: all should be good

- update deployment

Actual: all should be good

- delete deployment

Actual: all should be good. no errors in sentry.

https://www.loom.com/share/0201a21c990b4bdea196c86a526041aa

**Comment by fedorov-dualboot** [comment]
verified on prod. **OK**
Actual: all should be good. no errors in sentry.
